import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';import {fixtures} from './fixture.mjs';
const out=path.resolve('test-results/browser');await fs.mkdir(out,{recursive:true});
const fixtureDir=path.resolve(process.env.NATIVE_FIXTURES_DIR||'tests/fixtures/native');let docs={},texts={},native=true;
for(const role of ['baseline','operator','incoming','conflict'])try{texts[role]=await fs.readFile(path.join(fixtureDir,role==='conflict'?'incoming-conflict.json':role+'.json'),'utf8');docs[role]=JSON.parse(texts[role]);}catch{native=false;docs[role]=fixtures()[role];texts[role]=JSON.stringify(docs[role],null,2)+'\n';}
if(!native&&process.env.ALLOW_SYNTHETIC_BROWSER!=='1')throw new Error('Native OBS fixtures required for browser acceptance');
for(const role of ['baseline','operator','incoming','conflict'])await fs.writeFile(path.join(out,`${role}-input.json`),texts[role]);
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'4181'},stdio:['ignore','pipe','pipe']});
await new Promise((ok,no)=>{server.stdout.once('data',ok);server.once('error',no);setTimeout(()=>no(new Error('Server startup timed out')),10000).unref();});
let browser;try{browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/chromium',chromiumSandbox:true,headless:true,args:['--disable-dev-shm-usage']});}catch(error){server.kill();throw error;}
const context=await browser.newContext({viewport:{width:1440,height:1080},acceptDownloads:true,reducedMotion:'reduce'});await context.tracing.start({screenshots:true,snapshots:true,sources:true});
const page=await context.newPage();let errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{const u=route.request().url();if(!u.startsWith('http://127.0.0.1:4181')&&!u.startsWith('blob:')&&!u.startsWith('data:')){external.push(u);return route.abort();}return route.continue();});
const groups=[];const group=(name)=>groups.push(name);
async function screenshot(name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
async function upload(role,text=texts[role],name=role+'.json'){await page.locator('#'+role+'-file').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(text)});await expect(page.locator('#'+role+'-file-name')).toHaveText(name);}
async function loadInputs(conflict=false){await page.locator('#clear-button').click();for(const role of ['baseline','operator','incoming'])await upload(role,role==='incoming'&&conflict?texts.conflict:texts[role]);await page.locator('#analyze-button').click();await expect(page.locator('#review-content')).toBeVisible();}
async function saveDownload(selector,file){const waiting=page.waitForEvent('download');await page.locator(selector).click();const d=await waiting;await d.saveAs(path.join(out,file));return JSON.parse(await fs.readFile(path.join(out,file),'utf8'));}
try{
 await page.goto('http://127.0.0.1:4181');await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('#analyze-button')).toBeDisabled();await screenshot('01-ja-start');group('Japanese initial state and disabled exports');
 await page.keyboard.press('Tab');await expect(page.locator('.skip-link')).toBeFocused();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>location.hash),'#workspace');await page.locator('#tab-reconcile').focus();await page.keyboard.press('ArrowLeft');await expect(page.locator('#prepare-panel')).toBeVisible();await page.keyboard.press('ArrowRight');await expect(page.locator('#reconcile-panel')).toBeVisible();group('Keyboard skip link and tab navigation');
 await page.locator('#lang-en').click();await page.locator('#sample-button').click();await expect(page.locator('#review-content')).toBeVisible();await expect(page.locator('#build-button')).toBeEnabled();await page.locator('#filter-all').click();await screenshot('02-en-sample');group('English sample loads and one-sided edits reconcile');
 await loadInputs();await page.locator('#filter-all').click();await page.locator('#output-name').fill('SceneReconcile merged');await page.locator('#build-button').click();await expect(page.locator('#download-area')).toBeVisible();const merged=await saveDownload('#download-collection','merged.json');const receipt=await saveDownload('#download-receipt','merged.receipt.json');assert.equal(merged.sources.length,8);assert.equal(receipt.stats.sources,8);assert.match(await page.locator('#output-hash').textContent(),/^[0-9a-f]{64}$/);await screenshot('03-en-reviewed-export');group('Actual three native inputs and actual collection/receipt downloads');
 await loadInputs(true);await expect(page.locator('#build-button')).toBeDisabled();const operator=page.locator('input[type=radio][value=operator]');await expect(operator).toHaveCount(1);await operator.focus();await page.keyboard.press('Space');await expect(operator).toBeChecked();await expect(page.locator('#build-button')).toBeEnabled();await screenshot('04-conflict-operator-decision');await page.locator('#output-name').fill('SceneReconcile conflict resolved');await page.locator('#build-button').click();await expect(page.locator('#download-area')).toBeVisible();await saveDownload('#download-collection','conflict-resolved.json');await saveDownload('#download-receipt','conflict-resolved.receipt.json');group('Complete transform conflict blocks and keyboard decision preserves independent edits');
 await page.locator('#lang-ja').click();await expect(page.locator('input[type=radio][value=operator]')).toBeChecked();await screenshot('05-ja-conflict-decided');group('Language change preserves decisions and export identity');
 await upload('incoming',texts.incoming,'replacement.json');await expect(page.locator('#download-area')).toBeHidden();await expect(page.locator('#review-content')).toBeHidden();await expect(page.locator('#build-button')).toBeDisabled();group('Replacing one input invalidates decisions and previous exports');
 await page.locator('#tab-prepare').click();await upload('prepare',texts.baseline,'baseline-for-prepare.json');await page.locator('#prepare-name').fill('Native prepared');await page.locator('#prepare-button').click();await expect(page.locator('#prepared-files')).toBeVisible();for(const role of ['baseline','operator','incoming']){const copy=await saveDownload('#download-prepared-'+role,`prepared-${role}.json`);assert.deepEqual(copy.sources,docs.baseline.sources);assert.equal(copy.name,`Native prepared · ${role}`);}await screenshot('06-ja-prepare-downloads');await page.locator('#prepare-name').fill('Changed prefix');await expect(page.locator('#prepared-files')).toBeHidden();group('Actual three prepared-copy downloads preserve every source and item UUID');
 await page.locator('#clear-button').click();await expect(page.locator('#prepared-files')).toBeHidden();await page.locator('#tab-reconcile').click();await expect(page.locator('#input-counter')).toHaveText('0 / 3');await expect(page.locator('#review-content')).toBeHidden();await expect(page.locator('#download-area')).toBeHidden();group('Clear removes all inputs, decisions and every prepared/export link');
 await page.locator('#baseline-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await expect(page.locator('#notice')).toContainText('INVALID_JSON');await expect(page.locator('#analyze-button')).toBeDisabled();await screenshot('07-invalid-json');group('Invalid JSON is visible and cannot enable comparison');
 await loadInputs();const unknown=structuredClone(docs.incoming);unknown.unrecognized_semantic_setting={enabled:true};await upload('incoming',JSON.stringify(unknown),'unsupported.json');await page.locator('#analyze-button').click();await expect(page.locator('#build-button')).toBeDisabled();const exclude=page.locator('input[type=radio][value=exclude]');await expect(exclude).toHaveCount(1);await exclude.check();await page.locator('#build-button').click();await expect(page.locator('#download-area')).toBeVisible();const excluded=await saveDownload('#download-receipt','explicit-exclusion.receipt.json');assert.equal(excluded.excluded.length,1);await screenshot('08-explicit-unsupported-exclusion');group('Unsupported semantic changes require explicit recorded exclusion');
 // Delay only file reading; interact through normal UI to prove canceled promises cannot restore stale state.
 await page.evaluate(()=>{window.__originalFileArrayBuffer=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){const value=await window.__originalFileArrayBuffer.call(this);if(this.name.startsWith('slow'))await new Promise(r=>setTimeout(r,500));return value;};});
 await page.locator('#baseline-file').setInputFiles({name:'slow-cancel.json',mimeType:'application/json',buffer:Buffer.from(texts.baseline)});await expect(page.locator('#cancel-button')).toBeVisible();await page.locator('#cancel-button').click();await page.waitForTimeout(650);await expect(page.locator('#baseline-file-name')).not.toHaveText('slow-cancel.json');await expect(page.locator('#download-area')).toBeHidden();group('Cancel prevents a late file read restoring stale inputs');
 await page.locator('#baseline-file').setInputFiles({name:'slow-old.json',mimeType:'application/json',buffer:Buffer.from(texts.baseline)});await upload('baseline',texts.baseline,'newer.json');await page.waitForTimeout(650);await expect(page.locator('#baseline-file-name')).toHaveText('newer.json');group('Newer file selection wins over an older asynchronous read');
 await page.locator('#operator-file').setInputFiles({name:'slow-clear.json',mimeType:'application/json',buffer:Buffer.from(texts.operator)});await page.locator('#clear-button').click();await page.waitForTimeout(650);await expect(page.locator('#input-counter')).toHaveText('0 / 3');group('Clear during pending read stays cleared');
 await page.evaluate(()=>{File.prototype.arrayBuffer=window.__originalFileArrayBuffer;});await page.setViewportSize({width:390,height:844});await page.locator('#sample-button').click();await page.locator('#filter-all').click();await screenshot('09-ja-mobile-review');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile horizontal overflow');await page.locator('#lang-en').click();await page.locator('#tab-prepare').click();await screenshot('10-en-mobile-prepare');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'English mobile horizontal overflow');group('Japanese/English mobile fit at 390 pixels');
 assert.deepEqual(errors,[],'page errors');assert.deepEqual(external,[],'external network requests');await fs.writeFile(path.join(out,'results.json'),JSON.stringify({status:'pass',nativeFixtures:native,chromiumSandbox:true,browserVersion:browser.version(),groups,groupCount:groups.length,errors,externalRequests:external},null,2)+'\n');console.log(JSON.stringify({groupCount:groups.length,nativeFixtures:native,status:'pass'}));
}finally{await context.tracing.stop({path:path.join(out,'trace.zip')});await browser.close();server.kill();}
