import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {analyze,resolve,parseCollection,validateCollection,prepareCollection,affectedScenes,buildReceipt,sha256,TRANSFORM_FIELDS} from '../src/core.mjs';
import {fixtures,source,ids,item,scene,relative} from './fixture.mjs';
const fresh=()=>fixtures();const run=f=>{const {baseline,operator,incoming}=f;const p=analyze(baseline,operator,incoming);assert.deepEqual(p.errors,[]);return{p,r:resolve(p)}};
test('exact independent edit scenario: eight UUIDs, no source duplication',()=>{const f=fresh(),{r}=run(f);assert.equal(r.stats.sources,8);assert.equal(new Set(r.collection.sources.map(s=>s.uuid)).size,8);assert.deepEqual(source(r.collection,'Main').settings.items[1].pos,{x:240,y:80});const br=source(r.collection,'Break').settings.items[1];assert.deepEqual(br.pos,{x:40,y:30});assert.equal(br.visible,false);assert.equal(source(r.collection,'Title').settings.text,'Workshop begins at 18:30');assert.equal(source(r.collection,'Background').settings.color,4281541135);assert.equal(source(r.collection,'Thanks').settings.items[0].source_uuid,ids.LowerThird);assert.deepEqual(r.changes.find(x=>x.sourceName==='Title'&&x.kind==='source-settings').affectedScenes,['Break','LowerThird','Main','Thanks']);});
test('conflicting complete transform blocks; explicit operator retains independent incoming changes',()=>{const f=fresh();const p=analyze(f.baseline,f.operator,f.conflict);const conflict=p.units.filter(x=>x.status==='conflict');assert.equal(conflict.length,1);assert.throws(()=>resolve(p),/UNRESOLVED/);const r=resolve(p,{[conflict[0].id]:'operator'});assert.deepEqual(source(r.collection,'Main').settings.items[1].pos,{x:240,y:80});assert.equal(source(r.collection,'Title').settings.text,'Workshop begins at 18:30');assert.deepEqual(source(resolve(p,{[conflict[0].id]:'incoming'}).collection,'Main').settings.items[1].pos,{x:120,y:140});});
test('equal edits preserved without asking',()=>{const f=fresh();source(f.incoming,'Main').settings.items[1].pos={x:240,y:80};const {p}=run(f);assert.equal(p.units.find(x=>x.kind==='item-transform'&&x.sourceName==='Main').status,'equal');});
test('source array order is not identity',()=>{const f=fresh();f.incoming.sources.reverse();f.operator.sources.reverse();assert.equal(run(f).r.stats.sources,8);});
test('relative + absolute transform is one atom',()=>{const f=fresh();for(const k of Object.keys(f))f[k]=relative(f[k]);const {r}=run(f);const actual=source(r.collection,'Main').settings.items[1],expected=source(f.operator,'Main').settings.items[1];for(const k of TRANSFORM_FIELDS)assert.deepEqual(actual[k],expected[k]);});
test('mixed independent transform fields conflict atomically',()=>{const f=fresh();source(f.incoming,'Main').settings.items[1].crop_left=10;const p=analyze(f.baseline,f.operator,f.incoming);assert.equal(p.units.find(x=>x.kind==='item-transform'&&x.sourceName==='Main').status,'conflict');});
test('visibility and lock merge separately from transform',()=>{const f=fresh();source(f.incoming,'Break').settings.items[1].locked=true;const x=source(run(f).r.collection,'Break').settings.items[1];assert.equal(x.visible,false);assert.equal(x.locked,true);assert.equal(x.pos.x,40);});
test('source settings are atomic even when different settings changed',()=>{const f=fresh();source(f.incoming,'Background').settings.width=1200;const p=analyze(f.baseline,f.operator,f.incoming);assert.equal(p.units.find(x=>x.kind==='source-settings'&&x.sourceName==='Background').status,'conflict');});
test('reordered stack preserved as joint membership atom',()=>{const f=fresh();source(f.incoming,'Main').settings.items.reverse();const x=source(run(f).r.collection,'Main').settings.items;assert.deepEqual(x.map(y=>y.id),[2,1]);assert.equal(x[0].pos.x,240);});
test('different reorder needs explicit choice',()=>{const f=fresh();source(f.operator,'LowerThird').settings.items.reverse();source(f.incoming,'LowerThird').settings.items.push(item(3,'Background'));source(f.incoming,'LowerThird').settings.id_counter=3;const p=analyze(f.baseline,f.operator,f.incoming);assert.equal(p.units.find(x=>x.kind==='membership-order'&&x.sourceName==='LowerThird').status,'conflict');});
test('parallel new local integer IDs do not alias different source references',()=>{const f=fresh();for(const [doc,name] of [[f.operator,'Banner'],[f.incoming,'Title']]){const s=source(doc,'Main');s.settings.items.push(item(3,name));s.settings.id_counter=3;}const p=analyze(f.baseline,f.operator,f.incoming),u=p.units.find(x=>x.kind==='membership-order'&&x.sourceName==='Main');assert.equal(u.status,'conflict');const r=resolve(p,{[u.id]:'incoming'});assert.equal(source(r.collection,'Main').settings.items[2].source_uuid,ids.Title);});
test('parallel same reference new ID different placement selects whole added item',()=>{const f=fresh();for(const [doc,x] of [[f.operator,10],[f.incoming,30]]){const s=source(doc,'Main');s.settings.items.push(item(3,'Banner',x,0));s.settings.id_counter=3;}const p=analyze(f.baseline,f.operator,f.incoming),u=p.units.find(x=>x.kind==='membership-order'&&x.sourceName==='Main');assert.equal(u.status,'conflict');assert.equal(source(resolve(p,{[u.id]:'incoming'}).collection,'Main').settings.items[2].pos.x,30);});
test('remove versus edit never silently drops incoming edit',()=>{const f=fresh();source(f.operator,'Break').settings.items.pop();const p=analyze(f.baseline,f.operator,f.incoming),u=p.units.find(x=>x.kind==='scene-removal-edit');assert.equal(u.status,'conflict');assert.throws(()=>resolve(p),/UNRESOLVED/);assert.equal(source(resolve(p,{[u.id]:'incoming'}).collection,'Break').settings.items[1].pos.x,40);});
test('one-sided membership removal accepted',()=>{const f=fresh();source(f.incoming,'LowerThird').settings.items.pop();assert.equal(source(run(f).r.collection,'LowerThird').settings.items.length,1);});
test('capture/media settings operator-owned and incoming changes require recorded exclusion',()=>{const f=fresh();for(const d of [f.baseline,f.operator,f.incoming]){const s=source(d,'Banner');s.id='ffmpeg_source';s.versioned_id='ffmpeg_source';s.settings={local_file:'/operator/video.mp4'};}source(f.operator,'Banner').settings.local_file='/operator/new.mp4';source(f.incoming,'Banner').settings.local_file='/incoming/video.mp4';const p=analyze(f.baseline,f.operator,f.incoming),u=p.units.find(x=>x.kind==='source-settings'&&x.sourceName==='Banner');assert.equal(u.status,'unsupported');assert.throws(()=>resolve(p),/UNRESOLVED/);const r=resolve(p,{[u.id]:'exclude'});assert.equal(source(r.collection,'Banner').settings.local_file,'/operator/new.mp4');assert.equal(r.excluded.length,1);});
test('unknown incoming source semantics are explicit exclusions',()=>{const f=fresh();source(f.incoming,'Title').monitoring_type=2;const p=analyze(f.baseline,f.operator,f.incoming);assert.equal(p.units.find(x=>x.kind==='source-metadata'&&x.sourceName==='Title').status,'unsupported');});
test('unknown incoming top-level semantics are explicit exclusions',()=>{const f=fresh();f.incoming.unrecognized_native_setting={x:true};const p=analyze(f.baseline,f.operator,f.incoming);assert.equal(p.units.find(x=>x.id==='collection:unrecognized_native_setting').status,'unsupported');});
test('unsupported item blend changes require exclusion',()=>{const f=fresh();source(f.incoming,'Main').settings.items[0].blend_type='multiply';assert.equal(analyze(f.baseline,f.operator,f.incoming).units.find(x=>x.kind==='item-metadata').status,'unsupported');});
for(const [label,mutate,code] of [
 ['duplicate name',d=>{source(d,'Banner').name='Title'},'DUPLICATE_NAME'],
 ['duplicate UUID',d=>{source(d,'Banner').uuid=ids.Title},'DUPLICATE_UUID'],
 ['missing reference',d=>{source(d,'Main').settings.items[0].source_uuid=ids.Thanks},'MISSING_REFERENCE'],
 ['name fallback mismatch',d=>{source(d,'Main').settings.items[0].name='Title'},'REFERENCE_NAME_MISMATCH'],
 ['cycle',d=>{source(d,'LowerThird').settings.items.push(item(3,'Main'));source(d,'LowerThird').settings.id_counter=3},'NESTING_CYCLE'],
 ['group',d=>d.groups.push({}), 'GROUPS_UNSUPPORTED'],
 ['canvas',d=>d.canvases.push({}), 'CANVASES_UNSUPPORTED'],
 ['filter',d=>source(d,'Title').filters.push({id:'filter'}),'FILTERS_UNSUPPORTED'],
 ['custom plugin',d=>source(d,'Title').id='mystery_plugin','SOURCE_KIND_UNSUPPORTED'],
 ['script',d=>d.modules={'scripts-tool':[{}]},'SCRIPTS_UNSUPPORTED'],
 ['text file',d=>source(d,'Title').settings.from_file=true,'TEXT_FILE_UNSUPPORTED'],
 ['duplicate item ID',d=>source(d,'Main').settings.items[1].id=1,'ITEM_ID'],
 ['invalid counter',d=>source(d,'Main').settings.id_counter=0,'ITEM_COUNTER'],
 ['nonfinite transform',d=>source(d,'Main').settings.items[0].pos.x=Infinity,'NONFINITE_NUMBER'],
 ['partial relative',d=>d.version=2,'RELATIVE_TRANSFORM_REQUIRED'],
 ['scene order mismatch',d=>d.scene_order.pop(),'SCENE_ORDER_MEMBERSHIP'],
 ['unknown version',d=>d.version=5,'COORDINATE_VERSION'],
 ['custom size',d=>source(d,'Main').settings.custom_size=true,'CUSTOM_CANVAS_UNSUPPORTED']
])test('reject '+label,()=>{const d=fresh().baseline;mutate(d);assert.throws(()=>validateCollection(d),new RegExp(code));});
test('existing source deletion rejected, not guessed by name',()=>{const f=fresh();const s=source(f.incoming,'Title');s.uuid='20000000-0000-4000-8000-000000000006';source(f.incoming,'LowerThird').settings.items[1].source_uuid=s.uuid;const p=analyze(f.baseline,f.operator,f.incoming);assert.match(p.errors[0],/ANCESTRY_OR_DELETION/);});
test('same UUID source rename rejected',()=>{const f=fresh();source(f.incoming,'Title').name='NewTitle';source(f.incoming,'LowerThird').settings.items[1].name='NewTitle';assert.match(analyze(f.baseline,f.operator,f.incoming).errors[0],/IDENTITY_OR_RENAME/);});
test('resolution mismatch rejected',()=>{const f=fresh();f.incoming.resolution.x=1920;assert.match(analyze(f.baseline,f.operator,f.incoming).errors[0],/PROFILE_MISMATCH/);});
test('postmerge cycles are blocked even if each branch is acyclic',()=>{const f=fresh();source(f.operator,'Main').settings.items.push(item(3,'Break'));source(f.operator,'Main').settings.id_counter=3;source(f.incoming,'Break').settings.items.push(item(3,'Main'));source(f.incoming,'Break').settings.id_counter=3;assert.throws(()=>run(f),/NESTING_CYCLE/);});
test('postmerge duplicate new source names blocked',()=>{const f=fresh();f.operator.sources.push({...structuredClone(source(f.incoming,'ThanksText')),uuid:'20000000-0000-4000-8000-000000000008'});assert.throws(()=>run(f),/DUPLICATE_NAME/);});
test('disjoint additions union automatically',()=>{const f=fresh();f.operator.sources.push({...structuredClone(source(f.incoming,'ThanksText')),name:'OperatorText',uuid:'20000000-0000-4000-8000-000000000008'});assert.equal(run(f).r.stats.sources,9);});
test('changed collision UUID additions require whole-closure decision',()=>{const f=fresh();f.operator.sources.push(structuredClone(source(f.incoming,'ThanksText')));source(f.operator,'ThanksText').settings.text='Operator content';const p=analyze(f.baseline,f.operator,f.incoming);assert.equal(p.units.find(x=>x.kind==='added-source-closure').status,'conflict');});
test('three prepared copies have unique names and preserve full UUID and item identity',()=>{const d=fresh().baseline,p=prepareCollection(d);assert.equal(new Set(Object.values(p).map(x=>x.name)).size,3);for(const x of Object.values(p))assert.deepEqual(x.sources,d.sources);assert.equal(d.name,'Workshop baseline');});
test('prepare does not mutate input',()=>{const d=fresh().baseline,p=prepareCollection(d);p.operator.sources[0].name='Changed';assert.equal(d.sources[0].name,'Main');});
test('unrecognized JSON and prototype keys rejected',()=>{assert.throws(()=>parseCollection('{oops'),/INVALID_JSON/);assert.throws(()=>parseCollection('{"__proto__":{}}'),/UNSAFE_KEY/);});
test('file size bounded',()=>assert.throws(()=>parseCollection(' '.repeat(10*1024*1024+1)),/FILE_TOO_LARGE/));
test('depth bounded',()=>{let obj={};for(let n=0;n<65;n++)obj={nested:obj};assert.throws(()=>validateCollection(obj),/DEPTH_LIMIT/);});
test('SHA receipt binds exact input whitespace and exact output bytes',async()=>{const f=fresh(),{r}=run(f),records=Object.fromEntries(['baseline','operator','incoming'].map(k=>[k,{name:k+'.json',text:JSON.stringify(f[k],null,2)+'\n'}]));const text=JSON.stringify(r.collection,null,2)+'\n';const receipt=await buildReceipt(records,r,text);assert.equal(receipt.inputs.operator.sha256,await sha256(records.operator.text));assert.equal(receipt.output.sha256,await sha256(text));assert.notEqual(await sha256(text),await sha256(text.trim()));assert.equal(receipt.unresolved.length,0);});
test('inputs and plan are not mutated by decision resolution',()=>{const f=fresh(),before=JSON.stringify(f),p=analyze(f.baseline,f.operator,f.conflict),beforePlan=JSON.stringify(p),u=p.units.find(x=>x.status==='conflict');resolve(p,{[u.id]:'operator'});assert.equal(JSON.stringify(f),before);assert.equal(JSON.stringify(p),beforePlan);});
test('hidden transitive scenes remain in impact result',()=>{const f=fresh();assert.deepEqual(affectedScenes(f.operator,ids.Title),['Break','LowerThird','Main']);});
test('standalone native supported fixture test exports for oracle development',async()=>{const f=fresh(),{r}=run(f);await fs.mkdir('generated',{recursive:true});for(const [k,d]of Object.entries(f))await fs.writeFile(`generated/synthetic-${k}.json`,JSON.stringify(d,null,2)+'\n');await fs.writeFile('generated/synthetic-merged.json',JSON.stringify(r.collection,null,2)+'\n');});

test('duplicate JSON object keys rejected instead of silently taking last value',()=>{assert.throws(()=>parseCollection('{"name":"first","name":"second"}'),/DUPLICATE_JSON_KEY/);});
test('item counter reserves IDs used on either branch',()=>{const f=fresh();source(f.incoming,'Main').settings.id_counter=100;assert.equal(source(run(f).r.collection,'Main').settings.id_counter,100);});

test('malformed crop, alignment and bounds flags rejected',()=>{for(const [key,value,code] of [['crop_left',-1,'CROP_RANGE'],['align',3,'ALIGNMENT_RANGE'],['bounds_crop','yes','BOUNDS_CROP_FLAG'],['bounds_type',7,'BOUNDS_TYPE_RANGE']]){const d=fresh().baseline;source(d,'Main').settings.items[0][key]=value;assert.throws(()=>validateCollection(d),new RegExp(code));}});

test('UTF-8 BOM accepted only at beginning; exact byte hashing retains it',async()=>{const d=fresh().baseline,text='\ufeff'+JSON.stringify(d);assert.deepEqual(parseCollection(text),d);assert.notEqual(await sha256(text),await sha256(text.slice(1)));});
