import test from 'node:test';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';import fs from 'node:fs/promises';
import {analyze,resolve,validateCollection,parseCollection} from '../src/core.mjs';import {fixtures,item} from './fixture.mjs';
function maximum(){const base=fixtures().baseline;base.sources=[];base.scene_order=[];let seq=0;const id=()=>`30000000-0000-4000-8000-${String(++seq).padStart(12,'0')}`;
for(let n=0;n<180;n++)base.sources.push({uuid:id(),name:`Color ${n}`,id:'color_source',versioned_id:'color_source_v3',settings:{color:4278190080,width:100,height:100}});
for(let n=0;n<20;n++){const name=`Scene ${n}`;const items=Array.from({length:50},(_,j)=>({...item(j+1,'Background',j*10,j*5),source_uuid:base.sources[j].uuid,name:base.sources[j].name}));base.sources.push({uuid:id(),name,id:'scene',versioned_id:'scene',settings:{custom_size:false,id_counter:50,items}});base.scene_order.push({name});}base.current_scene=base.current_program_scene='Scene 0';return base;}
test('maximum supported collection validates exactly at 20/200/1000',()=>assert.deepEqual(validateCollection(maximum()),{sources:200,scenes:20,items:1000}));
test('200 source limit enforced',()=>{const d=maximum();d.sources.push({...structuredClone(d.sources[0]),uuid:'40000000-0000-4000-8000-000000000001',name:'Extra'});assert.throws(()=>validateCollection(d),/SOURCE_LIMIT/);});
test('20 scene limit enforced independently',()=>{const d=maximum();d.sources.shift();const s=structuredClone(d.sources.at(-1));s.name='Extra scene';s.uuid='40000000-0000-4000-8000-000000000001';s.settings.items=[];d.sources.push(s);d.scene_order.push({name:s.name});assert.throws(()=>validateCollection(d),/SCENE_LIMIT/);});
test('1000 item limit enforced',()=>{const d=maximum(),s=d.sources.at(-1);s.settings.items.push({...structuredClone(s.settings.items[0]),id:51});s.settings.id_counter=51;assert.throws(()=>validateCollection(d),/ITEM_LIMIT/);});
test('bounded worst-case review creates 1000 independent transform decisions under ten seconds',async()=>{const b=maximum(),o=structuredClone(b),i=structuredClone(b);for(const s of o.sources)if(s.id==='scene')for(const x of s.settings.items)x.pos.x+=10;for(const s of i.sources)if(s.id==='scene')for(const x of s.settings.items)x.pos.y+=10;const start=performance.now();const plan=analyze(b,o,i);const ms=performance.now()-start;assert.equal(plan.units.filter(x=>x.status==='conflict').length,1000);assert.ok(ms<10000,`analysis took ${ms}ms`);const r=resolve(plan,Object.fromEntries(plan.units.map(x=>[x.id,'operator'])));assert.equal(r.stats.items,1000);await fs.mkdir('evidence',{recursive:true});await fs.writeFile('evidence/bounded-benchmark.json',JSON.stringify({sources:200,scenes:20,items:1000,conflicts:1000,analyzeMs:ms,node:process.version,profile:'synthetic unit benchmark; not native consumer evidence'},null,2)+'\n');});
test('JSON scanner permits escaped strings, unicode keys and nested arrays',()=>{const d=fixtures().baseline;d.notes={text:'A \\" [,]}:',unicode:'日本語',values:[true,null,{name:'x'}]};assert.deepEqual(parseCollection(JSON.stringify(d)),d);});
