// Lightweight UI state checks. Rendering, native input events, accessibility, and actual downloads
// are covered separately by browser-test.mjs; this deliberately has no browser dependency.
import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import test from 'node:test';
import {webcrypto} from 'node:crypto';
import * as core from '../src/core.mjs';
import {fixtures} from './fixture.mjs';

test('UI state transitions, interrupted reads, and stable exports', async () => {
const nodes=new Map();let document;class Node{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attributes={};this.events={};this.hidden=false;this.value='';this.textContent='';this.open=false;this.className='';this.classList={toggle:(name,value)=>{const a=new Set(this.className.split(' '));value?a.add(name):a.delete(name);this.className=[...a].join(' ')}}}set id(v){this._id=v;nodes.set(v,this)}get id(){return this._id}setAttribute(k,v){this.attributes[k]=v}getAttribute(k){return this.attributes[k]}append(...v){this.children.push(...v)}replaceChildren(...v){this.children=v}addEventListener(k,v){this.events[k]=v}closest(){return this.card||(this.card=new Node('label'))}focus(){document.activeElement=this}scrollIntoView(){}remove(){}click(){this.events.click?.({target:this})}}
const html=await fs.readFile(new URL('../web/index.html', import.meta.url),'utf8');const staticNodes=[];for(const match of html.matchAll(/<([a-z][\w-]*)\b([^>]+)>/g)){const [,tag,attrs]=match;const n=new Node(tag);for(const [key,value]of [...attrs.matchAll(/([\w-]+)="([^"]*)"/g)].map(x=>[x[1],x[2]])){if(key==='id')n.id=value;else if(key==='class')n.className=value;else if(key==='value')n.value=value;else if(key.startsWith('data-'))n.dataset[key.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=value;else n.setAttribute(key,value)}n.hidden=/\bhidden\b/.test(attrs);n.disabled=/\bdisabled\b/.test(attrs);staticNodes.push(n)}
function descend(n){return [n,...n.children.filter(x=>typeof x==='object').flatMap(descend)]}
document={body:new Node('body'),documentElement:new Node('html'),activeElement:null,getElementById:id=>nodes.get(id),createElement:tag=>new Node(tag),createTextNode:text=>({textContent:text,children:[]}),querySelectorAll:selector=>selector==='details.unit[open]'?[...nodes.values()].flatMap(descend).filter(n=>n.tagName==='DETAILS'&&n.className.split(' ').includes('unit')&&n.open):staticNodes.filter(n=>selector==='[data-i18n]'?n.dataset.i18n:selector==='[data-i18n-html]'?n.dataset.i18nHtml:selector==='[data-i18n-aria]'?n.dataset.i18nAria:false)};
const context=vm.createContext({document,console,structuredClone,TextEncoder,TextDecoder,Blob,URL,setTimeout,clearTimeout,crypto:webcrypto,matchMedia:()=>({matches:true}),SCENE_SAMPLE:fixtures(),...core});context.globalThis=context;let code=await fs.readFile(new URL('../web/app.mjs', import.meta.url),'utf8');code=code.replace(/^import[^\n]+\n/,'');code+='\nglobalThis.testing={state,readFile,compare,prepare,build,cancel,clear,setLanguage,sample,pending,renderControls,renderReview};';vm.runInContext(code,context);const a=context.testing;const $=id=>nodes.get(id);const groups=[];const group=n=>groups.push(n);const file=(name,text)=>({name,size:Buffer.byteLength(text),arrayBuffer:async()=>new TextEncoder().encode(text).buffer});const docs=fixtures();const texts=Object.fromEntries(Object.entries(docs).map(([k,v])=>[k,JSON.stringify(v)]));
assert.equal($('analyze-button').disabled,true);assert.equal($('build-button').disabled,true);group('Initial controls disabled');
await a.sample();assert.equal(a.state.plan.errors.length,0);assert.equal(a.pending().length,0);await a.build();assert.ok(a.state.cache);assert.equal(a.state.cache.receipt.output.sha256,await core.sha256(a.state.cache.outputText));const cache=a.state.cache;a.setLanguage('en');assert.equal(a.state.cache,cache);group('Sample, comparison, stable hashed export and language preservation');
$('output-name').value='New name';$('output-name').events.input();assert.equal(a.state.cache,null);group('Output name invalidates export');
await a.readFile('incoming',file('conflict.json',texts.conflict));assert.equal(a.state.plan,null);await a.compare();assert.equal(a.pending().length,1);await a.build();assert.equal(a.state.cache,null);const u=a.pending()[0];a.state.decisions[u.id]='operator';a.renderReview();await a.build();assert.ok(a.state.cache);group('Input replacement invalidates; unresolved conflict blocks; choice enables output');
let done;const slow={name:'slow.json',size:100,arrayBuffer:()=>new Promise(r=>done=r)};const first=a.readFile('baseline',slow);await a.readFile('baseline',file('new.json',texts.baseline));done(new TextEncoder().encode(texts.baseline).buffer);await first;assert.equal(a.state.records.baseline.name,'new.json');group('New file wins over late old read');
const cancelled=a.readFile('operator',slow);a.cancel();done(new TextEncoder().encode(texts.operator).buffer);await cancelled;assert.equal(a.state.records.operator,undefined);assert.equal(a.state.cache,null);assert.equal(a.state.reading.size,0);group('Cancel prevents stale read and exports');
const cleared=a.readFile('incoming',slow);a.clear();done(new TextEncoder().encode(texts.incoming).buffer);await cleared;assert.equal(Object.keys(a.state.records).length,0);assert.equal(a.state.plan,null);assert.equal(a.state.cache,null);group('Clear prevents pending read restoration');
await a.readFile('baseline',file('bad.json','{bad'));assert.equal(a.state.docs.baseline,undefined);assert.match(a.state.notice.detail,/INVALID_JSON/);group('Invalid JSON rejects and reports');
await a.readFile('prepare',file('prepare.json',texts.baseline));await a.prepare();assert.equal(Object.keys(a.state.prepared).length,3);for(const role of ['baseline','operator','incoming'])assert.deepEqual(JSON.parse(a.state.prepared[role].text).sources,docs.baseline.sources);$('prepare-name').value='changed';$('prepare-name').events.input();assert.equal(a.state.prepared,null);group('Prepared copies retain sources and prefix invalidation');
a.clear();await a.sample();const p=a.build();a.clear();await p;assert.equal(a.state.cache,null);group('Clear interrupts pending export');

await a.sample();const bom='\uFEFF'+texts.baseline;await a.readFile('baseline',file('bom.json',bom));assert.equal(a.state.records.baseline.text,bom);await a.compare();await a.build();assert.equal(a.state.cache.receipt.inputs.baseline.sha256,await core.sha256(new TextEncoder().encode(bom)));group('UTF-8 BOM preserved in raw input hash');
await a.readFile('baseline',{name:'invalid-utf8.json',size:2,arrayBuffer:async()=>new Uint8Array([0xff,0xfe]).buffer});assert.equal(a.state.records.baseline,undefined);assert.match(a.state.notice.detail,/INVALID_UTF8/);group('Invalid UTF-8 explicitly rejected');
assert.equal(groups.length,12);
});
